openapi: 3.0.1
info:
  title: "Account Service - TraderX Spec-First"
  version: "1.0"
paths:
  /account/:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
    put:
      responses:
        "200":
          description: OK
  /account/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
        "404":
          description: Not found
  /accountuser/:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
        "404":
          description: Person not found
    put:
      responses:
        "200":
          description: OK
  /accountuser/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
        "404":
          description: Not found
