server.port=${POSITION_SERVICE_PORT:18090}

spring.datasource.url=jdbc:postgresql://${DATABASE_PG_HOST:localhost}:${DATABASE_PG_PORT:5432}/${DATABASE_NAME:traderx}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_DBUSER:traderx}
spring.datasource.password=${DATABASE_DBPASS:traderx}
spring.threads.virtual.enabled=true

server.max-http-request-header-size=1000000
