apiVersion: v1
kind: ConfigMap
metadata:
  name: traderx-mesh-prometheus-scrape
  namespace: traderx-mesh
data:
  scrape.yml: |
    - job_name: "trade-service"
      static_configs:
        - targets: ["trade-service.traderx-mesh.svc.cluster.local:8080"]
