apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: traderx
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: traderx/account-service:state009
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 18088
              protocol: TCP
          env:
            - name: ACCOUNT_SERVICE_PORT
              value: "18088"
            - name: DATABASE_PG_HOST
              value: "database"
            - name: DATABASE_PG_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "traderx"
            - name: DATABASE_DBUSER
              value: "traderx"
            - name: DATABASE_DBPASS
              value: "traderx"
            - name: PEOPLE_SERVICE_HOST
              value: "people-service"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://localhost:8080"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus,info"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
