apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-promtail-config
  namespace: traderx
data:
  config.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: traderx-pod-logs
        pipeline_stages:
          - cri: {}
          - regex:
              source: filename
              expression: '/var/log/pods/(?P<namespace>[^_]+)_(?P<pod>[^_]+)_(?P<pod_uid>[^/]+)/(?P<service>[^/]+)/.*'
          - labels:
              namespace:
              pod:
              service:
        static_configs:
          - targets: [localhost]
            labels:
              compose_project: traderx-state-009
              job: traderx-docker
              __path__: /var/log/pods/traderx_*/*/*.log
