apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: traderx
  labels:
    app: tempo
spec:
  type: ClusterIP
  selector:
    app: tempo
  ports:
    - name: http
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
