apiVersion: v1
kind: Service
metadata:
  name: web-front-end-angular
  namespace: traderx
  labels:
    app: web-front-end-angular
spec:
  type: ClusterIP
  selector:
    app: web-front-end-angular
  ports:
    - name: http
      protocol: TCP
      port: 18093
      targetPort: 18093
