#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_ID="006-tilt-kubernetes-dev-loop"
PARENT_STATE_ID="004-kubernetes-runtime"
TARGET_ROOT="${ROOT}/generated/code/target-generated"
STATE_OUT="${TARGET_ROOT}/tilt-kubernetes-dev-loop"
PARENT_OUT="${TARGET_ROOT}/kubernetes-runtime"
PARENT_BUILD_PLAN="${PARENT_OUT}/build-plan.json"
PARENT_MANIFEST_DIR="${PARENT_OUT}/manifests/base"
TILT_DIR="${STATE_OUT}/tilt"

if ! command -v jq >/dev/null 2>&1; then
  echo "[fail] jq command is required"
  exit 1
fi

# Build on top of state 004 assets and image build plan.
bash "${ROOT}/pipeline/generate-state.sh" "${PARENT_STATE_ID}"

[[ -f "${PARENT_BUILD_PLAN}" ]] || {
  echo "[fail] missing parent build plan: ${PARENT_BUILD_PLAN}"
  exit 1
}

[[ -d "${PARENT_MANIFEST_DIR}" ]] || {
  echo "[fail] missing parent manifests: ${PARENT_MANIFEST_DIR}"
  exit 1
}

rm -rf "${STATE_OUT}"
mkdir -p "${TILT_DIR}" "${STATE_OUT}/spec-source" "${STATE_OUT}/manifests"

cp -R "${PARENT_MANIFEST_DIR}" "${STATE_OUT}/manifests/base"
cp "${PARENT_BUILD_PLAN}" "${STATE_OUT}/upstream-build-plan.json"

{
  cat <<'EOF'
# Generated by pipeline/generate-state-006-tilt-kubernetes-dev-loop.sh
# State: 006-tilt-kubernetes-dev-loop

allow_k8s_contexts('kind-traderx-state-004', 'minikube')

# Reuse generated Kubernetes manifests from state 004 baseline.
k8s_yaml('../manifests/base/*.yaml')

EOF
  while IFS= read -r item; do
    name="$(jq -r '.name' <<<"${item}")"
    image="$(jq -r '.image' <<<"${item}")"
    context_rel="$(jq -r '.context' <<<"${item}")"
    dockerfile_rel="$(jq -r '.dockerfile' <<<"${item}")"
    context_path="../${context_rel}"
    dockerfile_path="../${context_rel}/${dockerfile_rel}"

    cat <<EOF
docker_build(
    '${image}',
    '${context_path}',
    dockerfile='${dockerfile_path}',
)
k8s_resource('${name}')

EOF
  done < <(jq -c '.images[]' "${PARENT_BUILD_PLAN}")
  cat <<'EOF'
# Helpful local forwards while iterating.
k8s_resource('edge-proxy', port_forwards=['8080:8080'])
k8s_resource('web-front-end-angular', port_forwards=['18093:18093'])
EOF
} > "${TILT_DIR}/Tiltfile"

cat > "${TILT_DIR}/tilt-settings.json" <<'EOF'
{
  "stateId": "006-tilt-kubernetes-dev-loop",
  "inheritsFrom": "004-kubernetes-runtime",
  "primaryEntrypoints": [
    "http://localhost:8080",
    "http://localhost:10350"
  ],
  "notes": [
    "Run start-state-006 first to ensure baseline Kubernetes runtime is available.",
    "Then run tilt up from this directory."
  ]
}
EOF

cat > "${TILT_DIR}/README.md" <<'EOF'
# State 006 Tilt Dev Loop Assets

This directory contains generated Tilt assets for TraderX state `006-tilt-kubernetes-dev-loop`.

Quick start:

```bash
./scripts/start-state-006-tilt-kubernetes-dev-loop-generated.sh --provider kind --skip-build
cd generated/code/target-generated/tilt-kubernetes-dev-loop/tilt
tilt up
```

URLs:

- App entrypoint: `http://localhost:8080`
- Tilt UI: `http://localhost:10350`
EOF

cp "${ROOT}/specs/006-tilt-kubernetes-dev-loop/spec.md" "${STATE_OUT}/spec-source/spec.md"
cp "${ROOT}/specs/006-tilt-kubernetes-dev-loop/requirements/functional-delta.md" "${STATE_OUT}/spec-source/functional-delta.md"
cp "${ROOT}/specs/006-tilt-kubernetes-dev-loop/requirements/nonfunctional-delta.md" "${STATE_OUT}/spec-source/nonfunctional-delta.md"
cp "${ROOT}/specs/006-tilt-kubernetes-dev-loop/contracts/contract-delta.md" "${STATE_OUT}/spec-source/contract-delta.md"

cat > "${STATE_OUT}/README.md" <<'EOF'
# State 006 Tilt Local Dev Loop Artifacts

Generated from:

- `specs/006-tilt-kubernetes-dev-loop/**`
- `generated/code/target-generated/kubernetes-runtime/build-plan.json`

State intent:

- preserve state 004 runtime behavior,
- add Tilt-driven local Kubernetes development workflow artifacts.

Artifacts:

- Tiltfile: `tilt/Tiltfile`
- Tilt state metadata: `tilt/tilt-settings.json`
- Copied k8s manifests baseline: `manifests/base`
- Parent image map reference: `upstream-build-plan.json`

Run baseline runtime for this state:

```bash
./scripts/start-state-006-tilt-kubernetes-dev-loop-generated.sh --provider kind
```

Run state smoke tests:

```bash
./scripts/test-state-006-tilt-kubernetes-dev-loop.sh
```

Optional Tilt command flow (requires `tilt`):

```bash
cd generated/code/target-generated/tilt-kubernetes-dev-loop/tilt
tilt up
```
EOF

bash "${ROOT}/pipeline/generate-state-architecture-doc.sh" "${STATE_ID}"

cat <<EOF
[summary] state=${STATE_ID}
[summary] parent-state=${PARENT_STATE_ID}
[summary] impacted-assets=tiltfile,tilt-settings,kubernetes-manifest-overlay
[summary] generated-path=generated/code/target-generated/tilt-kubernetes-dev-loop
[summary] runtime-entrypoint=./scripts/start-state-006-tilt-kubernetes-dev-loop-generated.sh
EOF
