#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GENERATED_ROOT="${TRADERX_GENERATED_ROOT:-${ROOT}/generated}"
TARGET_ROOT="${GENERATED_ROOT}/code/target-generated"
UPSTREAM_DIR="${TARGET_ROOT}/kubernetes-runtime"
STATE_DIR="${TARGET_ROOT}/tilt-kubernetes-dev-loop"
MANIFEST_DIR="${STATE_DIR}/manifests/base"
TILT_DIR="${STATE_DIR}/tilt"
UPSTREAM_BUILD_PLAN="${UPSTREAM_DIR}/build-plan.json"

for required in "${UPSTREAM_BUILD_PLAN}" "${UPSTREAM_DIR}/manifests/base"; do
  [[ -e "${required}" ]] || {
    echo "[fail] required state 010 artifact missing for state 011 render: ${required}"
    exit 1
  }
done

rm -rf "${STATE_DIR}"
mkdir -p "${MANIFEST_DIR}" "${TILT_DIR}" "${STATE_DIR}/spec-source"

cp -R "${UPSTREAM_DIR}/manifests/base/." "${MANIFEST_DIR}/"
cp "${UPSTREAM_BUILD_PLAN}" "${STATE_DIR}/upstream-build-plan.json"

for source in spec.md requirements/functional-delta.md requirements/nonfunctional-delta.md contracts/contract-delta.md; do
  src_path="${ROOT}/specs/011-tilt-kubernetes-dev-loop/${source}"
  [[ -f "${src_path}" ]] || continue
  cp "${src_path}" "${STATE_DIR}/spec-source/$(basename "${source}")"
done

cat > "${STATE_DIR}/README.md" <<'EOF'
# State 011 Tilt Local Dev Loop Artifacts

Generated from:

- `specs/011-tilt-kubernetes-dev-loop/**`
- `generated/code/target-generated/kubernetes-runtime/build-plan.json`

State intent:

- preserve state 010 runtime behavior,
- add Tilt-driven local Kubernetes development workflow artifacts.

Artifacts:

- Tiltfile: `tilt/Tiltfile`
- Tilt state metadata: `tilt/tilt-settings.json`
- Copied k8s manifests baseline: `manifests/base`
- Parent image map reference: `upstream-build-plan.json`

Run baseline runtime for this state:

```bash
./scripts/start-state-011-tilt-kubernetes-dev-loop-generated.sh --provider kind
```

Run state smoke tests:

```bash
./scripts/test-state-011-tilt-kubernetes-dev-loop.sh
```

Optional Tilt command flow (requires `tilt`):

```bash
cd generated/code/target-generated/tilt-kubernetes-dev-loop/tilt
tilt up
```
EOF

KIND_CLUSTER_NAME="traderx-state-011"

cat > "${TILT_DIR}/tilt-settings.json" <<EOF
{
  "stateId": "011-tilt-kubernetes-dev-loop",
  "inheritsFrom": "010-kubernetes-runtime",
  "clusterName": "${KIND_CLUSTER_NAME}",
  "primaryEntrypoints": [
    "http://localhost:8080"
  ],
  "notes": [
    "Run start-state-010 to ensure baseline Kubernetes runtime is available.",
    "Then run tilt up from this directory."
  ]
}
EOF

{
  echo "# Generated by pipeline/render-state-011-tilt-kubernetes-dev-loop.sh"
  echo "# State: 011-tilt-kubernetes-dev-loop"
  echo
  echo "allow_k8s_contexts('kind-traderx-state-010', 'traderx-state-010', 'kind-traderx-state-011', 'traderx-state-011', 'kind-traderx-state-012', 'traderx-state-012', 'minikube')"
  echo
  echo "k8s_yaml('../manifests/base/*.yaml')"
  echo
  while IFS= read -r item; do
    image="$(jq -r '.image' <<<"${item}")"
    context_rel="$(jq -r '.context' <<<"${item}")"
    dockerfile_rel="$(jq -r '.dockerfile' <<<"${item}")"
    echo "docker_build('${image}', '../${context_rel}', dockerfile='../${context_rel}/${dockerfile_rel}')"
  done < <(jq -c '.images[]' "${UPSTREAM_BUILD_PLAN}")
  echo
  while IFS= read -r deployment; do
    echo "k8s_resource('${deployment}')"
  done < <(jq -r '.deployments[]' "${UPSTREAM_BUILD_PLAN}")
} > "${TILT_DIR}/Tiltfile"

cat > "${TILT_DIR}/README.md" <<'EOF'
# Tilt Dev Loop (State 011)

This Tilt project reuses state 010 manifests and image mappings.

Run:

```bash
tilt up
```

Prerequisite:

```bash
./scripts/start-state-011-tilt-kubernetes-dev-loop-generated.sh --provider kind
```
EOF

echo "[done] rendered state 011 tilt artifacts into ${STATE_DIR}"
