FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src/PeopleService.WebApi
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 18089
ENV PEOPLE_SERVICE_PORT=18089
ENTRYPOINT ["dotnet", "PeopleService.WebApi.dll"]
