kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: traderx-state-010
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
