apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traderx-mesh
resources:
  - namespace.yaml
  - peerauthentication-mtls.yaml
  - gateway.yaml
  - destinationrule.yaml
  - virtualservice-trade-service.yaml
  - networkpolicy-default-deny.yaml
