# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/java/.devcontainer/base.Dockerfile

# [Choice] Java version (use -bullseye variants on local arm64/Apple Silicon): 11, 17, 11-bullseye, 17-bullseye, 11-buster, 17-buster
ARG VARIANT="17-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/java:0-${VARIANT}

WORKDIR /database
COPY . .

EXPOSE 18082
EXPOSE 18083
EXPOSE 18084

RUN ./gradlew build
RUN chmod +x ./run.sh
ENTRYPOINT ./run.sh 