server.port=${ORDER_MATCHER_PORT:18110}

spring.datasource.url=jdbc:postgresql://${DATABASE_PG_HOST:localhost}:${DATABASE_PG_PORT:5432}/${DATABASE_NAME:traderx}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_DBUSER:traderx}
spring.datasource.password=${DATABASE_DBPASS:traderx}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false
spring.threads.virtual.enabled=true

order.matcher.price-service-url=${PRICE_SERVICE_URL:http://${PRICE_SERVICE_HOST:localhost}:18100}
order.matcher.trade-service-url=${TRADE_SERVICE_URL:http://${TRADE_SERVICE_HOST:localhost}:18092/trade/}
order.matcher.tick-ms=${ORDER_MATCHER_TICK_MS:1000}
order.matcher.fill-full-threshold=${ORDER_FILL_FULL_THRESHOLD:1000}
order.matcher.seed-enabled=${ORDER_MATCHER_SEED_ENABLED:true}
nats.address=${NATS_ADDRESS:nats://${NATS_BROKER_HOST:localhost}:4222}

# To avoid "Request header is too large" when application is backed by oidc proxy.
server.max-http-request-header-size=1000000

logging.level.root=info
