apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: traderx
  labels:
    app: blackbox-exporter
spec:
  type: ClusterIP
  selector:
    app: blackbox-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9115
      targetPort: 9115
