apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: traderx
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.25.0
          imagePullPolicy: IfNotPresent
          args: ["--config.file=/etc/blackbox_exporter/config.yml"]
          ports:
            - name: http
              containerPort: 9115
              protocol: TCP
          volumeMounts:
            - name: blackbox-config
              mountPath: /etc/blackbox_exporter/config.yml
              subPath: blackbox.yml
      volumes:
        - name: blackbox-config
          configMap:
            name: observability-blackbox-config
