apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: traderx
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: pg
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: "traderx"
            - name: POSTGRES_USER
              value: "traderx"
            - name: POSTGRES_PASSWORD
              value: "traderx"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: database-init-sql
              mountPath: /docker-entrypoint-initdb.d/001-initialSchema.sql
              subPath: 001-initialSchema.sql
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U traderx -d traderx"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U traderx -d traderx"]
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: db-data
          emptyDir: {}
        - name: database-init-sql
          configMap:
            name: database-init-sql
