apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-broker
  namespace: traderx
  labels:
    app: nats-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-broker
  template:
    metadata:
      labels:
        app: nats-broker
    spec:
      containers:
        - name: nats-broker
          image: nats:2.14-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 4222
              protocol: TCP
            - name: monitor
              containerPort: 8222
              protocol: TCP
            - name: ws
              containerPort: 8081
              protocol: TCP
          args: ["-c", "/etc/nats/nats.conf"]
          volumeMounts:
            - name: nats-config
              mountPath: /etc/nats/nats.conf
              subPath: nats.conf
      volumes:
        - name: nats-config
          configMap:
            name: nats-config
