apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-matcher
  namespace: traderx
  labels:
    app: order-matcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-matcher
  template:
    metadata:
      labels:
        app: order-matcher
    spec:
      containers:
        - name: order-matcher
          image: traderx/order-matcher:state009
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 18110
              protocol: TCP
          env:
            - name: ORDER_MATCHER_PORT
              value: "18110"
            - name: DATABASE_PG_HOST
              value: "database"
            - name: DATABASE_PG_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "traderx"
            - name: DATABASE_DBUSER
              value: "traderx"
            - name: DATABASE_DBPASS
              value: "traderx"
            - name: NATS_BROKER_HOST
              value: "nats-broker"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://localhost:8080"
            - name: PRICE_SERVICE_URL
              value: "http://price-publisher:18100"
            - name: TRADE_SERVICE_URL
              value: "http://trade-service:18092/trade/"
            - name: ORDER_MATCHER_TICK_MS
              value: "1000"
            - name: ORDER_FILL_FULL_THRESHOLD
              value: "1000"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus,info"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
