apiVersion: v1
kind: Service
metadata:
  name: order-matcher
  namespace: traderx
  labels:
    app: order-matcher
spec:
  type: ClusterIP
  selector:
    app: order-matcher
  ports:
    - name: http
      protocol: TCP
      port: 18110
      targetPort: 18110
