apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: traderx
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: prometheus
      protocol: TCP
      port: 8889
      targetPort: 8889
    - name: health
      protocol: TCP
      port: 13133
      targetPort: 13133
