apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-publisher
  namespace: traderx
  labels:
    app: price-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-publisher
  template:
    metadata:
      labels:
        app: price-publisher
    spec:
      containers:
        - name: price-publisher
          image: traderx/price-publisher:state009
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 18100
              protocol: TCP
          env:
            - name: PRICE_PUBLISHER_PORT
              value: "18100"
            - name: NATS_BROKER_HOST
              value: "nats-broker"
            - name: PRICE_BOOTSTRAP_MODE
              value: "snapshot"
            - name: PRICE_TICKERS
              value: "AAPL,MSFT,AMZN,GOOGL,META,NVDA,TSLA,IBM,BAC,C,JPM,GS,MS,UBS,DB,COF,DFS,FNMA,FIS,FNF"
