apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: traderx
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: grafana/promtail:2.9.8
          imagePullPolicy: IfNotPresent
          args: ["-config.file=/etc/promtail/config.yaml"]
          ports:
            - name: http
              containerPort: 3101
              protocol: TCP
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail/config.yaml
              subPath: config.yaml
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: run
              mountPath: /run/promtail
      volumes:
        - name: promtail-config
          configMap:
            name: observability-promtail-config
        - name: varlogpods
          hostPath:
            path: /var/log/pods
            type: DirectoryOrCreate
        - name: run
          emptyDir: {}
