apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: traderx
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.5.0
          imagePullPolicy: IfNotPresent
          args: ["-config.file=/etc/tempo/config.yaml"]
          ports:
            - name: http
              containerPort: 3200
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo/config.yaml
              subPath: config.yaml
      volumes:
        - name: tempo-config
          configMap:
            name: observability-tempo-config
