apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-processor
  namespace: traderx
  labels:
    app: trade-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-processor
  template:
    metadata:
      labels:
        app: trade-processor
    spec:
      containers:
        - name: trade-processor
          image: traderx/trade-processor:state009
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 18091
              protocol: TCP
          env:
            - name: TRADE_PROCESSOR_SERVICE_PORT
              value: "18091"
            - name: DATABASE_PG_HOST
              value: "database"
            - name: DATABASE_PG_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "traderx"
            - name: DATABASE_DBUSER
              value: "traderx"
            - name: DATABASE_DBPASS
              value: "traderx"
            - name: NATS_BROKER_HOST
              value: "nats-broker"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://localhost:8080"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus,info"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
