module.exports = {
  mainSidebar: [
    'home',
    {
      type: 'doc',
      id: 'blog/index',
      label: 'Engineering Blog',
    },
    {
      type: 'category',
      label: 'Start Here',
      items: [
        'spec-kit/index',
        'spec-kit/why-speckit',
        'spec-kit/spec-kit-generation-guide',
        'spec-kit/spec-kit-workflow',
        'spec-kit/state-docs',
        'spec-kit/convergence-states',
        'spec-kit/generated-state-branches',
        'spec-kit/run-generated-overlays',
        'spec-kit/baseline-vs-parity',
      ],
    },
    {
      type: 'category',
      label: 'SpecKit Sources',
      items: [
        'spec-kit/spec-kit-portal',
        {
          type: 'link',
          label: 'Spec Catalog',
          href: '/specs',
        },
        {
          type: 'link',
          label: 'Constitution',
          href: '/specify/memory/constitution',
        },
        {
          type: 'link',
          label: 'Spec API Explorer',
          href: '/api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Learning Paths',
      items: [
        'learning/index',
        'learning/state-001-baseline-uncontainerized-parity',
        'learning/state-002-edge-proxy-uncontainerized',
        'learning/state-003-containerized-compose-runtime',
        'learning/state-004-postgres-database-replacement',
        'learning/state-005-messaging-nats-replacement',
        'learning/state-006-observability-lgtm-compose',
        'learning/state-007-pricing-awareness-market-data',
        'learning/state-008-order-management-matcher',
        'learning/state-009-kubernetes-runtime',
        'learning/state-010-tilt-kubernetes-dev-loop',
        'learning/state-011-platform-convergence-c3',
        'learning/state-012-radius-kubernetes-platform',
        'learning-paths/index',
        'spec-kit/visual-learning-graphs',
        'spec-kit/spec-kit-learning-path-strategy',
        'spec-kit/state-transition-generation-plan',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Project ADRs',
          items: [
            {
              type: 'autogenerated',
              dirName: 'adr',
            },
          ],
        },
        'spec-kit/api-explorer',
        {
          type: 'link',
          label: 'Official Spec Kit Docs',
          href: 'https://github.github.com/spec-kit/index.html',
        },
      ],
    },
  ],
}
