module.exports = {
  mainSidebar: [
    'home',
    {
      type: 'link',
      label: 'Migration TODO',
      href: '/traderspec-specs/migration-todo',
    },
    {
      type: 'link',
      label: 'Migration Blog',
      href: '/traderspec-specs/migration-blog',
    },
    {
      type: 'category',
      label: 'Spec Kit',
      items: [
        'traderspec/spec-kit-portal',
        'traderspec/spec-kit-workflow',
        {
          type: 'link',
          label: 'Spec Kit Requirements Catalog',
          href: '/traderspec-specs/specs',
        },
        {
          type: 'link',
          label: 'Spec Kit .specify',
          href: '/traderspec-specs/specify',
        },
        {
          type: 'link',
          label: 'Official Spec Kit Docs',
          href: 'https://github.github.com/spec-kit/index.html',
        },
      ],
    },
    'learning-paths/index',
    {
      type: 'category',
      label: 'TraderSpec',
      items: [
        'traderspec/index',
        'traderspec/spec-migration-journey',
        'traderspec/baseline-vs-parity',
        'traderspec/spec-first-regeneration',
        'traderspec/run-base-uncontainerized-hydrated',
        'traderspec/run-generated-overlays',
        'traderspec/run-specfirst-generated-codebase',
        'traderspec/component-cutover-matrix',
        'traderspec/visual-learning-graphs',
      ],
    },
    {
      type: 'category',
      label: 'Guide',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide',
        },
      ],
    },
    'roadmap',
    'team',
  ],
}
