module.exports = {
  mainSidebar: [
    'home',
    {
      type: 'link',
      label: 'Migration TODO',
      href: '/traderspec-specs/migration-todo',
    },
    {
      type: 'link',
      label: 'Migration Blog',
      href: '/traderspec-specs/migration-blog',
    },
    {
      type: 'category',
      label: 'Spec Kit',
      items: [
        'traderspec/spec-kit-workflow',
        {
          type: 'link',
          label: 'Spec Kit Requirements Catalog',
          href: '/traderspec-specs/speckit',
        },
      ],
    },
    'learning-paths/index',
    {
      type: 'category',
      label: 'TraderSpec',
      items: [
        {
          type: 'autogenerated',
          dirName: 'traderspec',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guide',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide',
        },
      ],
    },
    'roadmap',
    'team',
  ],
}
