#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TARGET_ROOT="${1:-${ROOT}/generated/code/target-generated}"
STATE_ID="${2:-004-containerized-compose-runtime}"
OUT_DIR="${TARGET_ROOT}/custom-overlays/custom-001-managed-postgres-runtime"
OUT_FILE="${OUT_DIR}/db.env"

mkdir -p "${OUT_DIR}"

find "${TARGET_ROOT}" -type f \( -name "docker-compose.yml" -o -name "compose.yaml" \) -print0 2>/dev/null \
  | while IFS= read -r -d '' file; do
      if grep -Eq 'image:[[:space:]]*postgres' "${file}"; then
        echo "[rule] RULE-DB-001: postgres image reference detected: ${file}"
      fi
    done

cat > "${OUT_FILE}" <<EOF2
# Generated by apply-managed-postgres-endpoint-example.sh
POSTGRES_HOST=managed-postgres-${STATE_ID}.internal.example
POSTGRES_PORT=5432
POSTGRES_SSLMODE=verify-full
POSTGRES_CLIENT_CERT=/etc/internal-certs/postgres/client.crt
POSTGRES_CLIENT_KEY=/etc/internal-certs/postgres/client.key
POSTGRES_CA_CERT=/etc/internal-certs/postgres/ca.crt
EOF2

echo "[ok] wrote managed postgres runtime overlay: ${OUT_FILE}"
