name: traderx-004-containerized-compose-runtime-ghcr

services:
  database:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: database
    image: ghcr.io/finos/traderx-c0/database:${TRADERX_IMAGE_TAG:-latest}
    build: null
  reference-data:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: reference-data
    image: ghcr.io/finos/traderx-c0/reference-data:${TRADERX_IMAGE_TAG:-latest}
    build: null
  trade-feed:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: trade-feed
    image: ghcr.io/finos/traderx-c0/trade-feed:${TRADERX_IMAGE_TAG:-latest}
    build: null
  people-service:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: people-service
    image: ghcr.io/finos/traderx-c0/people-service:${TRADERX_IMAGE_TAG:-latest}
    build: null
  account-service:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: account-service
    image: ghcr.io/finos/traderx-c0/account-service:${TRADERX_IMAGE_TAG:-latest}
    build: null
  position-service:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: position-service
    image: ghcr.io/finos/traderx-c0/position-service:${TRADERX_IMAGE_TAG:-latest}
    build: null
  trade-processor:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: trade-processor
    image: ghcr.io/finos/traderx-c0/trade-processor:${TRADERX_IMAGE_TAG:-latest}
    build: null
  trade-service:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: trade-service
    image: ghcr.io/finos/traderx-c0/trade-service:${TRADERX_IMAGE_TAG:-latest}
    build: null
  web-front-end-angular:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: web-front-end-angular
    image: ghcr.io/finos/traderx-c0/web-front-end-angular:${TRADERX_IMAGE_TAG:-latest}
    build: null
  ingress:
    extends:
      file: ../../../containerized-compose/docker-compose.yml
      service: ingress
    image: ghcr.io/finos/traderx-c0/ingress:${TRADERX_IMAGE_TAG:-latest}
    build: null
