name: traderx-007-observability-lgtm-compose-ghcr

services:
  database:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: database
    restart: unless-stopped
  reference-data:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: reference-data
    restart: unless-stopped
    image: ghcr.io/finos/traderx-c1/reference-data:${TRADERX_IMAGE_TAG:-latest}
    build: null
  nats-broker:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: nats-broker
    restart: unless-stopped
  people-service:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: people-service
    restart: unless-stopped
    image: ghcr.io/finos/traderx-c1/people-service:${TRADERX_IMAGE_TAG:-latest}
    build: null
  account-service:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: account-service
    restart: unless-stopped
    image: ghcr.io/finos/traderx-c1/account-service:${TRADERX_IMAGE_TAG:-latest}
    build: null
  position-service:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: position-service
    restart: unless-stopped
    image: ghcr.io/finos/traderx-c1/position-service:${TRADERX_IMAGE_TAG:-latest}
    build: null
  trade-processor:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: trade-processor
    restart: unless-stopped
    image: ghcr.io/finos/traderx-c1/trade-processor:${TRADERX_IMAGE_TAG:-latest}
    build: null
  trade-service:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: trade-service
    restart: unless-stopped
    image: ghcr.io/finos/traderx-c1/trade-service:${TRADERX_IMAGE_TAG:-latest}
    build: null
  web-front-end-angular:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: web-front-end-angular
    restart: unless-stopped
    image: ghcr.io/finos/traderx-c1/web-front-end-angular:${TRADERX_IMAGE_TAG:-latest}
    build: null
  ingress:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: ingress
    restart: unless-stopped
    image: ghcr.io/finos/traderx-c1/ingress:${TRADERX_IMAGE_TAG:-latest}
    build: null
  otel-collector:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: otel-collector
    restart: unless-stopped
  blackbox-exporter:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: blackbox-exporter
    restart: unless-stopped
  prometheus:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: prometheus
    restart: unless-stopped
  loki:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: loki
    restart: unless-stopped
  promtail:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: promtail
    restart: unless-stopped
  tempo:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: tempo
    restart: unless-stopped
  grafana:
    extends:
      file: ../../../observability-lgtm-compose/docker-compose.yml
      service: grafana
    restart: unless-stopped

volumes:
  postgres_state_009_data: {}
